### ISSUE TITLE
Error collecting metrics when RedisBungee is not installed

### ISSUE THREAD

**Issue by Maescool** [weihao/bungeecord-prometheus-exporter#101]
When RedisBungee is not installed i get this when getting /metrics

```
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI
	at org.akadia.prometheus.bungeecord.metrics.RedisBungeeOnlinePlayer.doCollect(RedisBungeeOnlinePlayer.java:16) ~[?:?]
	at org.akadia.prometheus.interfaces.Metric.collect(Metric.java:22) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.akadia.prometheus.MetricRegistry.collectMetrics(MetricRegistry.java:26) ~[?:?]
	at org.akadia.prometheus.MetricsServer$1.handle(MetricsServer.java:43) ~[?:?]
	...

```

redis things are disabled in the config

**Comment by weihao** [comment]
Plug-in version?

**Comment by Maescool** [comment]
latest release 3.2.2

**Comment by weihao** [comment]
```
22:52:40 [INFO] [BungeeCordPrometheusExporter] redis_player_connects is disabled in the config
22:52:40 [INFO] [BungeeCordPrometheusExporter] redis_player_disconnects is disabled in the config
22:52:40 [INFO] [BungeeCordPrometheusExporter] redis_online_player is disabled in the config
22:52:40 [INFO] [BungeeCordPrometheusExporter] redis_bungee_online_proxies is disabled in the config
22:52:40 [INFO] jetty-11.0.14; built: 2023-02-22T23:41:48.575Z; git: 4601fe8dd805ce75b69c64466c115a162586641b; jvm 19.0.1+10-21
22:52:41 [INFO] Started ServerConnector@107ed6fc{HTTP/1.1, (http/1.1)}{kubernetes.docker.internal:9985}
22:52:41 [INFO] Started Server@20b5f2ac{STARTING}[11.0.14,sto=0] @11979ms
22:52:41 [INFO] [BungeeCordPrometheusExporter] Started Prometheus metrics endpoint at: 127.0.0.1:9985
22:52:41 [INFO] [BungeeCordPrometheusExporter] Initialized completed
22:52:41 [INFO] Enabled plugin BungeeCordPrometheusExporter version 3.2.2 by akadia
```

can't reproduce. the config should default to disabled for redis, can you regen the config again?

**Comment by Maescool** [comment]
It triggers as soon as you get the /metrics

**Comment by weihao** [comment]
Are you using velocity or bungeecord?

**Comment by Maescool** [comment]
Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526
This is the full trace:

```
[14:32:15 WARN] [org.eclipse.jetty.server.HttpChannel]: /metrics
 java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI
 	at org.akadia.prometheus.bungeecord.metrics.RedisBungeeOnlinePlayer.doCollect(RedisBungeeOnlinePlayer.java:16) ~[?:?]
 	at org.akadia.prometheus.interfaces.Metric.collect(Metric.java:22) ~[?:?]
 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
 	at org.akadia.prometheus.MetricRegistry.collectMetrics(MetricRegistry.java:26) ~[?:?]
 	at org.akadia.prometheus.MetricsServer$1.handle(MetricsServer.java:43) ~[?:?]
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[?:?]
 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
 	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[?:?]
 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[?:?]
 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[?:?]
 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[?:?]
 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[?:?]
 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[?:?]
 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[?:?]
 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[?:?]
 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[?:?]
 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[?:?]
 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[?:?]
 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[?:?]
 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[?:?]
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936) ~[?:?]
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080) ~[?:?]
 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
 Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungeeAPI
 	... 24 more

```

**Comment by Maescool** [comment]
Ok, my bad,
Seems the config had to be re-done, had redis_online_players, now it is redis_online_player
Thanks
