### ISSUE TITLE
No plugin.yml in src folder

### ISSUE THREAD

**Issue by ItsRainingHP** [weihao/bungeecord-prometheus-exporter#39]
I get the following error using your jar. Fails to initialize:

```[19:46:40] [Server thread/ERROR]: Could not load 'plugins\bungeecord-prometheus-exporter-3.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[paper-1.18.1.jar:git-Paper-75]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-75]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-75]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-75]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
    ... 7 more```

**Comment by weihao** [comment]
You can't run bungeecord prometheus exporter in a craftbukkit server because you need a proxy.

if you want to run a bukkit prometheus exporter, use https://github.com/sladkoff/minecraft-prometheus-exporter
