### ISSUE TITLE
I can't open x.x.x.x/metrics

### ISSUE THREAD

**Issue by Fumio-26** [weihao/bungeecord-prometheus-exporter#55]
11:44:50 [WARNING] FAILED Server@6f2cb653{FAILED}[11.0.7,sto=0]: java.io.IOException: Failed to bind to x.x.x.x/x.x.x.x:25589
java.io.IOException: Failed to bind to x.x.x.x/x.x.x.x:25589
    at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:305)
    at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:401)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    at org.eclipse.jetty.server.Server.doStart(Server.java:397)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at org.akadia.prometheus.MetricsServer.start(MetricsServer.java:60)
    at org.akadia.prometheus.bungeecord.PrometheusBungeeCordExporter.startMetricsServer(PrometheusBungeeCordExporter.java:90)
    at org.akadia.prometheus.bungeecord.PrometheusBungeeCordExporter.onEnable(PrometheusBungeeCordExporter.java:39)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.net.BindException: Cannot assign requested address
    at java.base/sun.nio.ch.Net.bind0(Native Method)
    at java.base/sun.nio.ch.Net.bind(Net.java:555)
    at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
    at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
    at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:340)
    ... 21 more

I've opened the port

**Comment by weihao** [comment]
is port 25589 taken? are you running in a container?

**Comment by Fumio-26** [comment]
ah sorry, now fixed
