### ISSUE TITLE
Missing  bungeecord-prometheus-exporter.jar file

### ISSUE THREAD

**Issue by lslamp** [weihao/bungeecord-prometheus-exporter#69]
After digging around I managed to find a file called "bungeecord-prometheus-exporter-main.zip".
I downloaded this and placed it into the plugin directory.
First Question, I am not clear if this plugin can work aside the referring plugin called "minecraft-prometheus-exporter-master.zip" I already have this dashboard up and running. I did not think that it would be any different because it seemed to deliver some different data.
The full error is below.

[08:58:11] [Server thread/ERROR]: Could not load 'plugins/bungeecord-prometheus-exporter-3.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:143) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:409) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3539-Spigot-56be6a8-82f7574]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:224) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3539-Spigot-56be6a8-82f7574]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3539-Spigot-56be6a8-82f7574]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3539-Spigot-56be6a8-82f7574]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

First question can the two plugins live side by side?
If the answer is yes, where can I get the plugin.yml file for the bungeecord plugin?

Thanks
Lawrence

**Comment by weihao** [comment]
download the jar file from the latest release: https://github.com/weihao/bungeecord-prometheus-exporter/releases/latest

you downloaded the wrong file

**Comment by lslamp** [comment]
@weihao Thanks for the pointer.

Can you tell me if this plugin works with the prometheus explorer loaded as well?

Thanks
Lawrence

**Comment by lslamp** [comment]
@weihao I tried uploading teh new file and got teh same error. I can only assume that it cannot be loaded with the other monitor.

Lawrence

**Comment by weihao** [comment]
it can, but you need to make sure there is no other monitor using the same port. also this plugin only runs on java 11+

**Comment by lslamp** [comment]
The error I am seeing has nothing to do with ports, it is complaining about plugin.yml missing.
That is very strange.
I thought that the first time you started minecraft with the .jar file in the plugin dir, then it will deploy but not run because it still needs to update the config. The error appears but no plugin dir is created and no config file is dropped.

Lawrence

**Comment by weihao** [comment]
it is a bungeecord plugin, it doesn't have a `plugin.yml`
